name: "paynext"
services:
  database:
    container_name: paynext-database
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: paynext-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: .env
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5433/postgres
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8001:8080"

volumes:
  pgdata:
